### ISSUE TITLE
HTML is not highlighted in WebStorm

### ISSUE THREAD

**Issue by branneman** [paularmstrong/Swig.tmbundle#2]
WebStorm has [Textmate bundles support](https://www.jetbrains.com/phpstorm/webhelp/importing-textmate-bundles.html), but I'm not getting this bundle to work as expected.

How do I get Swig code **and HTML** code highlighted in the same file in WebStorm on Windows?

This is what I get:
![webstorm-swig](https://cloud.githubusercontent.com/assets/172579/5043470/c011818e-6be5-11e4-9140-58a0cebd83ad.png)

I've tried installing and enabling the HTML textmate bundle as well, but when both the HTML and the Swig bundle are activated, the code is highlighted as only HTML. If I disable the HTML bundle but have the Swig bundle still active, I only get Swig highlighting.

**Read more:** http://stackoverflow.com/questions/26913637/webstorm-syntax-highlighting-for-swig-template-engine

**Comment by branneman** [comment]
Is my assumption correct that the bundle tries to _extend_ the HTML TextMate Bundle, but that extending is not supported in WebStorm, while it is supported in TextMate?

**Comment by branneman** [comment]
Also, would it then be a solution to stop extending the html bundle, and add the definitions for html to the swig bundle as well? Then it would be fully stand-alone, right?

**Comment by paularmstrong** [comment]
Feel free to fork as a separate bundle specifically for WebStorm. I don't think I'd merge in changes since this works just fine for TextMate. Also, I'm not really supporting this anymore. You would probably be fine with jinja/twig bundles as well.
